In [1]:
import pandas as pd
import numpy as np

In [2]:
car = pd.read_csv('quikr_car.csv')

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
car.shape

(892, 6)

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [6]:
#dataset backup
backup=car.copy()

# Data Preprocessing

In [7]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [8]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [9]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [10]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [11]:
car['name'].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P',
       'I want to sell my car Tata Zest', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat', 'Toyota Corolla',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Maruti Suzuki Alto 800 Lxi', 'Hindustan Motors Ambassador',
       'Toyota Corolla Altis 1.8 GL', 'Toyota Corolla Altis 1.8 J',
       'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Datsun Redi GO T O',
       'Maruti Suzuki Swift RS VDI', 'Fiat Punto Emotion 1.2',
       'Hyundai i10 Sportz 1.2', 'Chevrolet Beat LT Opt Diesel',
       'Chevrolet Beat LS Diesel', 'Tata Indigo CS',
       'Maruti Suzuki Swift VDi', 'Hyundai Eon Era Plus',
       'Mahindra XUV500', 'Ford Fiesta', 'Maruti Suzuki Wagon R',
       'Hyundai i20', 'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX',
       'Commercial , DZire LDI, 2016, for sale', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Tata indigo ecs LX, 201', 'Mahindra Scorpio SLX',
       'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII', 'MARUTI SUZUKI DESI',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX', 'Yama',
       'Maruti Suzuki Swift LDi', 'Mahindra TUV300 T4 Plus',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III',
       'Tata Indica eV2 LS', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'selling car Ta',
       'Honda City 1.5 V MT Exclusive', 'Chevrolet Spark LT 1.0 Airbag',
       'Tata Indigo eCS VX CR4 BS IV', 'Tata Zest 90',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Maruti Suzuki Swift Dzire car',
       'Hyundai Verna 1.4 VTVT', 'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Swift Dzire Tour (Gat',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'URJE',
       'Hyundai Santro Xing GLS', 'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Swift Dzire Tour 27 Dec 2016 Regis', 'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Tata zest x', 'Mahindra xyl',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Used Commercial Maruti Omn',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Wagon R Select Variant',
       'Tata Nano Lx BSIV', 'Jaguar XE XE Portfolio',
       'Hyundai Xcent S 1.2', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Toyota Innova 2.0 V',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Hyun', 'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Datsun Go Plus T O',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Commercial Chevrolet Sail Hatchback ca', 'Hyundai Xcent SX 1.2',
       'Tata Nano LX Special Edition', 'Commercial Car Ta',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'tata Indica', 'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Used bt new conditions ta', 'Renault Kwid 1.0', 'Sale tata',
       'Tata Venture EX 8 STR', 'Maruti Suzuki Swift Dzire Tour LXi',
       'Maruti Suzuki Alto LX BSII', 'Skoda Octavia Classic 1.9 TDI MT',
       'Maruti Suzuki Omni LPG BS IV', 'Tata Sumo Gold EX BS IV',
       'Tata indigo 2017 top model..', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Tata indigo', 'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV',
       'very good condition tata bolts are av', 'Toyota Innova 2.0 G4',
       'Sale Hyundai xcent commerc', 'Maruti Suzuki Swift VDi ABS',
       'Hyundai Elite i20 Asta 1.2', 'Volkswagen Polo Trendline 1.5L D',
       'Toyota Etios Liva Diesel', 'Maruti Suzuki Ciaz ZXi Plus RS',
       'Hyundai Elantra 1.8 S', 'Ford EcoSport Trend 1.5L Ti VCT',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI',
       'I want to sell my commercial car due t',
       'Hyundai Santro AE GLS Audio',
       'i want sale my car.no emi....uber atta', 'Tata ZEST 6 month old',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'MARUTI SUZUKI ERTIGA F', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ', 'Tata Nexon', 'Tata',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       '2012 Tata Sumo Gold f', 'Mahindra Xylo E8 BS IV',
       'Well mentained Tata Sumo',
       'all paper updated tata indica v2 and u',
       'Maruti Ertiga showroom condition with',
       '7 SEATER MAHINDRA BOLERO IN VERY GOOD', '9 SEATER MAHINDRA BOL',
       'scratch less Tata I', 'Maruti Suzuki swift dzire for sale in',
       'Commercial Chevrolet beat for sale in',
       'urgent sell my Mahindra qu', 'Tata Sumo Gold FX BSIII',
       'sell my car Maruti Suzuki Swif',
       'Maruti Suzuki Swift Dzire good car fo', 'Hyunda',
       'Commercial Maruti Suzuki Alto Lxi 800', 'urgent sale Ta',
       'Maruti Suzuki Alto vxi t', 'tata', 'TATA INDI', 'Hyundai Creta',
       'Tata Bolt XM Petrol', 'Hyundai Venue', 'Maruti Suzuki Ritz',
       'Renault Lodgy', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Any type car avaiabel hare...comercica', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS',
       'Volkswagen Vento Highline Plus 1.5 Diesel', 'Tata Manza',
       'Toyota Innova 2.0 G1 Petrol 8seater', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Alto 800 Select Variant',
       'Maruti Suzuki Ritz VXI ABS', 'tata zest 2017 f',
       'Tata Indica V2 DLE BS III', 'Ta', 'Tata Zest XM Diesel',
       'Honda Amaze 1.2 E i VTEC', 'Chevrolet Sail 1.2 LT ABS'],
      dtype=object)

Findings:
year has many non-year values
Price has Ask for Price and it is an object need to convert it into int
kms_driven has object values with kms at last.Need to extract int value. It has nan values and two rows have 'Petrol' in them.
Nan values in fuel_type
names are pretty inconsistent mixture of numerical and categorical data: Need to convert it into categorical data

In [12]:
car = car[car['year'].str.isnumeric()] #drop non numeric data

In [13]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '2003', '2004', '1995', '2002', '2001'], dtype=object)

In [14]:
car['year']=car['year'].astype(int) #convert dtype from object to numeric

In [15]:
car['year'].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [16]:
car=car[car['Price']!='Ask For Price'] # drop Ask For Price from price col

In [17]:
car['Price']

0        80,000
1      4,25,000
3      3,25,000
4      5,75,000
6      1,75,000
         ...
886    3,00,000
888    2,60,000
889    3,90,000
890    1,80,000
891    1,60,000
Name: Price, Length: 819, dtype: object

In [18]:
car['Price'] = car['Price'].str.replace(',','') #removing comma from price

In [19]:
car['Price']=car['Price'].astype(int)

In [20]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [21]:
#remove kms and commas
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','') #split by space and keep Ist element

In [22]:
car['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 819, dtype: object

In [23]:
car=car[car['kms_driven'].str.isnumeric()] #drop non numeric values from kms_driven

In [24]:
car['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 817, dtype: object

In [25]:
car['kms_driven']=car['kms_driven'].astype(int)

In [26]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [27]:
car = car[~car['fuel_type'].isna()] #excluding nan values

In [28]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ') #first three words of name

In [29]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [30]:
car.reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [31]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

Around 75% of cars are of 4.91 but max is 8.5 it might be outlier

In [32]:
car = car[car['Price']<6e6].reset_index(drop=True) #outlier only values less than 6e6

In [33]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [34]:
car.to_csv('Cleaned_Car_data.csv')

# Model

In [35]:
X = car.drop(columns = 'Price') #input features
y = car['Price'] #target

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

In [38]:
ohe = OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']]) #one hot encoding of all categorical columns

OneHotEncoder()

In [39]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [40]:
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

ColumnTransformer allows different preprocessing for different columns.
Here, it one-hot encodes 'name', 'company', and 'fuel_type', while keeping all other columns unchanged.

In [41]:
column_trans = make_column_transformer((OneHotEncoder(categories= ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [42]:
lr = LinearRegression()

make_pipeline(column_trans, lr) creates a pipeline that first applies the column transformer (column_trans) to preprocess the data, then fits a linear regression model (lr

In [43]:
pipe = make_pipeline(column_trans,lr)

In [44]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [45]:
y_pred = pipe.predict(X_test)
y_pred

array([ 2.83801971e+05,  5.88363597e+05,  6.19235524e+05,  7.25860134e+05,
        4.30569533e+05,  3.87823545e+05,  6.37275784e+04,  1.78567843e+06,
        2.61817279e+04,  7.09284144e+05,  1.81573069e+05,  6.37962620e+04,
        3.80892569e+05,  5.39215255e+05,  2.17075334e+05,  5.62185476e+05,
        2.40593720e+05,  3.40878587e+05,  4.46351783e+05,  5.65752084e+05,
        3.87823545e+05,  1.98369647e+05,  5.97496579e+05,  5.15609285e+05,
        8.15252395e+05,  2.88129814e+05, -7.27802082e+04,  3.65550794e+03,
        2.51486492e+05,  4.19842800e+05,  5.07501226e+05,  3.66335624e+04,
        4.20303476e+05,  4.30704531e+05,  5.20550162e+05,  4.54607168e+05,
        1.58425724e+06,  5.59060547e+05,  3.59104209e+05,  5.64842601e+05,
        2.92339955e+05,  4.30677356e+04,  5.90786252e+05,  5.97493999e+05,
        2.96195757e+05,  3.16569984e+05,  2.95231237e+05,  8.83868142e+05,
        4.17813822e+05,  6.00021310e+05,  1.49176097e+05,  2.39761583e+05,
        2.10362194e+05,  4.35340378e+05,  2.78246328e+05,  2.45243660e+05,
        6.15245558e+05,  3.56671937e+05,  2.56538031e+05,  3.16883426e+05,
        1.92332328e+05,  6.65240929e+05,  3.66516045e+05,  3.16569984e+05,
        3.00104709e+05,  6.78163391e+05,  5.84661451e+05,  3.03048853e+05,
        3.91238717e+05,  2.25819989e+06,  4.18328854e+05,  3.05651108e+05,
        2.64442930e+05,  6.41691845e+04,  2.32668797e+05,  4.70486302e+05,
        3.36066322e+05,  2.40613471e+05,  3.27365069e+05,  3.70874445e+05,
        6.10443285e+05, -7.13997079e+04,  2.80864626e+05,  3.27466836e+05,
        3.92904836e+05,  4.86650870e+05,  5.56803494e+04,  9.56345590e+05,
        3.18229950e+05,  4.13748305e+05,  3.22299351e+05,  1.72198578e+05,
        6.12303182e+05,  5.01792000e+05,  2.11755766e+05,  6.30094292e+05,
        6.30279809e+05, -1.69487203e+05,  6.41344250e+04,  3.28286205e+05,
        1.32763918e+05,  6.36081673e+05,  1.98527214e+05,  2.97412400e+05,
        1.44242524e+05,  5.68562394e+05, -5.56646252e+03,  2.69899122e+05,
        2.61219202e+05,  5.49145227e+05,  2.32668797e+05,  5.03280808e+05,
        5.25006949e+05,  3.38126246e+05,  3.16539135e+05,  4.66206040e+04,
        1.46426874e+06,  3.15482716e+05,  4.57050488e+05,  2.71364092e+05,
        5.97496579e+05,  8.26238389e+02,  4.17137496e+05,  2.03604870e+05,
        5.00621832e+05,  3.43646026e+05,  3.75641151e+05,  3.59720816e+05,
       -1.53125348e+05,  1.89522914e+05,  9.79957598e+04,  3.70019846e+05,
        3.67346399e+05,  5.43155023e+05,  4.13365974e+05,  1.57599733e+05,
        2.65427920e+05,  6.28421723e+05,  3.69246999e+05,  4.50973657e+05,
        5.23342389e+05,  6.52565250e+05,  2.93540422e+05,  2.59212437e+05,
        8.93605110e+04,  7.38052012e+05,  5.01453837e+05,  2.06564958e+05,
        4.79885349e+05,  1.52983367e+06,  2.36871829e+04,  3.65671131e+05,
        2.47714895e+05,  3.17630057e+05,  9.36674117e+04,  2.18221292e+05,
        4.06698911e+05,  1.36483711e+05,  2.32180384e+05,  5.99013733e+05,
        3.87698057e+05,  4.66762732e+05,  4.65983544e+04])

In [46]:
r2_score(y_test,y_pred)

0.7134742835417056

In [47]:
#Finding best random split to improve r2 score
scores = []
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6590606986986713 0
0.4786257606517895 1
0.6208927556399633 2
0.5370940474939164 3
0.8189008914026968 4
0.663459255693474 5
0.6276680933808616 6
0.6298983985249655 7
0.6720881094088995 8
0.5700791953589901 9
0.6909564138750743 10
0.608593435931707 11
0.45702298004916775 12
0.6673651317131507 13
0.6592450651142208 14
0.6880720177998594 15
0.4878848740099684 16
0.6657624655015627 17
0.6089491103896374 18
0.6034074870171284 19
0.6410904385506166 20
0.6211456334849963 21
0.7365509377530779 22
0.6403423971537936 23
0.5492145974423499 24
0.49865417690543823 25
0.673283566986147 26
0.7415621076879948 27
0.7254654037227812 28
0.6010256105848701 29
0.6245275902070402 30
0.6282641948514842 31
0.7693541851896373 32
0.7854399455824898 33
0.5622376315162908 34
0.6775368360245603 35
0.5645102583083262 36
0.6170618289779525 37
0.5392504757852616 38
0.7164028866735945 39
0.3261467222451033 40
0.6733770287242047 41
0.5833019420040901 42
0.6660295975859818 43
0.680697752648153 44
0.6975030453808673 45
0.5258710823297501 46
0.5882084589672656 47
0.7540194253355409 48
0.6861745074784078 49
0.5038151721390834 50
0.6016219699979741 51
0.6325679093210248 52
0.6638866885210654 53
0.5464591390192607 54
0.6975018704571333 55
0.7171721489088163 56
0.7195081396337553 57
0.7559060743040356 58
0.4842789105659331 59
0.5907561172722927 60
0.5244366061113179 61
0.43303330557429554 62
0.6189051096924959 63
0.6075252580190805 64
0.6417297864791376 65
0.4810956562101891 66
0.6590611490427842 67
0.621458596560554 68
0.7354721721055452 69
0.6997058604454744 70
0.7185795038334946 71
0.5796214507422974 72
0.6844480279531078 73
0.5518436152951169 74
0.5835282157024451 75
0.4492844761722624 76
0.5987008256174624 77
0.5738718638189394 78
0.6460754909789148 79
0.5624258089661682 80
0.6174561892208218 81
0.687176495764249 82
0.7370427159391439 83
0.6389605438051933 84
0.6359728201070897 85
0.6852118762791541 86
0.5373334372102541 87
0.6029768968789487 88
0.6383836525923339 89
0.6810584511411777 90
0.618213463914604 91
0.6883264387128805 92
0.49449112652673766 93
0.6331515641996147 94
0.6589828755263538 95
0.6367481082882165 96
0.6856533578493136 97
0.6751763020205748 98
0.5854412235771336 99
0.6898981488489998 100
0.6600103734863441 101
0.6837475458198212 102
0.6239882778858244 103
0.7041417654923494 104
0.5649580413296509 105
0.607863864267838 106
0.5764016992826534 107
0.5851263198057963 108
0.7107043286936141 109
0.6766897511725458 110
0.6556225524672227 111
0.5454221210825374 112
0.6956062078807983 113
0.6852731796540699 114
0.5672029937124694 115
0.5902140915834564 116
0.6525835354764538 117
0.5318378445323417 118
0.7228169023094384 119
0.6582063841363789 120
0.5953254004165018 121
0.7075031010762705 122
0.626097070520748 123
0.821603552521181 124
0.6810052818767534 125
0.6377198082201663 126
0.6239460020818663 127
0.5857196648236125 128
0.5503874487390326 129
0.6062874633794052 130
0.5323278679221998 131
0.6286237232678866 132
0.5821226461185953 133
0.765899788905742 134
0.7148772247594372 135
0.5440254002179092 136
0.7128697273305589 137
0.6643538942401548 138
0.5590399615820276 139
0.7181467106990109 140
0.5867175534332769 141
0.6612005972931894 142
0.7142582215495055 143
0.6245366258689611 144
0.5547108934354763 145
0.6686151701773695 146
0.5880601785866518 147
0.5635065717777559 148
0.6131500117288092 149
0.6277223908345391 150
0.7724673069820488 151
0.5656182742487026 152
0.5011968166041125 153
0.6341353056207243 154
0.6588059832283124 155
0.4158233820741183 156
0.7311954090010611 157
0.6310086722082916 158
0.6780739464354614 159
0.6478168281017616 160
0.5931058364394781 161
0.6642549400231151 162
0.5706458986648685 163
0.5895670920805927 164
0.6903209555164562 165
0.6648356433678783 166
0.49139466563646017 167
0.5687479091581051 168
0.6963051478160508 169
0.6905601976948099 170
0.6498581512476982 171
0.8102972752330023 172
0.7188900600942058 173
0.5410059153174549 174
0.6143168712844425 175
0.6726250584173863 176
0.6112667882474145 177
0.7143627442063589 178
0.6795703985382573 179
0.641430462217651 180
0.6170284476795227 181
0.6744808808291989 182
0.6389167331097856 183
0.5049470541299259 184
0.6668450511335571 185
0.7358301868693484 186
0.6871284570799838 187
0.6894377064586009 188
0.5728618805859187 189
0.7042424607524868 190
0.6646764844944437 191
0.5790542207930622 192
0.6910788511927745 193
0.7401877223242983 194
0.6272203582600799 195
0.6315943244917128 196
0.7493891295892506 197
0.4023034173422173 198
0.7100659401351396 199
0.7154890445378123 200
0.45223616014260926 201
0.6098712290476729 202
0.7847821697512498 203
0.5829277021428132 204
0.6723284618995617 205
0.7711475673108398 206
0.570583823855126 207
0.6767043190312357 208
0.3007969131110366 209
0.4925876904418538 210
0.5097737188873681 211
0.5691089786701615 212
0.6186079107643749 213
0.6758805498219118 214
0.6179571164499786 215
0.5303632527322459 216
0.6145645120034141 217
0.5417925297532102 218
0.5753604653892532 219
0.5905186102665381 220
0.681859160397132 221
0.4755140180276791 222
0.4958122956493103 223
0.5517617471296787 224
0.7244100926184562 225
0.7406367722942607 226
0.6401161374301698 227
0.7309063077450088 228
0.5909540061590629 229
0.5522565972768192 230
0.5916505124773684 231
0.6308099417513515 232
0.44074210933582203 233
0.724503888672152 234
0.5866992374932174 235
0.6673652115033948 236
0.6090862936896115 237
0.5266611082677892 238
0.5940223573647083 239
0.5705695783598339 240
0.48454569806997605 241
0.5170355142029665 242
0.6399801206152403 243
0.49584456395626253 244
0.7213153902693538 245
0.77963656531438 246
0.7463369584564137 247
0.779954576844012 248
0.5432062636389657 249
0.6070783519669012 250
0.5083577419387207 251
0.5594171938952597 252
0.6509987876676591 253
0.5879799634803424 254
0.7699614219308915 255
0.5590143543117163 256
0.7200649735784267 257
0.6313836849015084 258
0.5644972405544615 259
0.7154189111163578 260
0.7578331610146332 261
0.7048061356946511 262
0.7261648816097074 263
0.6347440830665367 264
0.6262102771872724 265
0.6583225192250056 266
0.6530165542528926 267
0.4747599729199863 268
0.5341025764034967 269
0.6272567010989092 270
0.5494578565289405 271
0.6220528908863366 272
0.6177490587077896 273
0.6693855802445632 274
0.6261404626660126 275
0.7534608342085576 276
0.6969020988009184 277
0.6287169545305855 278
0.7884249837584936 279
0.6615727843792553 280
0.6544444388099634 281
0.6888523257696462 282
0.734444861528311 283
0.7173674028491605 284
0.5664224138735982 285
0.7224952452029909 286
0.5928009478535305 287
0.3853192396000734 288
0.45188035986338737 289
0.5201089392806928 290
0.6938362221589243 291
0.5406856467502548 292
0.7510931539500434 293
0.8132009950810395 294
0.6309615381471254 295
0.7431482332164057 296
0.701007525330389 297
0.533034933581567 298
0.7071364238833013 299
0.7691687131967349 300
0.6807435204547074 301
0.7634435824362362 302
0.48723133669093743 303
0.6517725438933655 304
0.5961544707882538 305
0.7821691836893324 306
0.6917950141309088 307
0.6490594169871154 308
0.6969599244755685 309
0.6748877912545557 310
0.6297667197466037 311
0.5082827510893086 312
0.49945923551210947 313
0.528268117867815 314
0.7374767857403134 315
0.5830914970722517 316
0.6074521952184803 317
0.6538505684685401 318
0.5117569089368648 319
0.4756574784325557 320
0.5931684731989242 321
0.5330513058176947 322
0.5698582562925489 323
0.6196570480196253 324
0.5365474514809006 325
0.5928046429839822 326
0.7232909129341554 327
0.732681365504969 328
0.5143816435586376 329
0.6442379940323483 330
0.4964228981989237 331
0.6222138480256213 332
0.5731484242544624 333
0.6979472969840373 334
0.6015690101373686 335
0.5096222311454031 336
0.6709073389580886 337
0.6187278737123758 338
0.5840136918596129 339
0.7393344297123197 340
0.7318982626069748 341
0.5999971482494988 342
0.6714103048181586 343
0.6914623162704865 344
0.6448842686368549 345
0.6863190289474841 346
0.5894748191840518 347
0.710032183860182 348
0.6224942462843583 349
0.7435923660084359 350
0.7074651502846552 351
0.5742202947687631 352
0.4603117927250837 353
0.728603820922259 354
0.6677530763454882 355
0.6985494138819816 356
0.6490906396413217 357
0.7076083574926444 358
0.5834397741413087 359
0.7067968539904582 360
0.6772141407387129 361
0.5385365299822676 362
0.6878072571418059 363
0.7148915631999533 364

0.5631720175724044 365
0.6819750107291537 366
0.38912057019782886 367
0.7160664635956726 368
0.7463280020689274 369
0.6780450460972915 370
0.6248927253015294 371
0.643449298483669 372
0.6603135617249558 373
0.5183377156189681 374
0.5618644128073051 375
0.684573479217186 376
0.6171610010495179 377
0.735143321748968 378
0.7702030235043499 379
0.6528481998072638 380
0.6988550360159502 381
0.7054411267861405 382
0.8058705240414508 383
0.688728844156588 384
0.704705499056032 385
0.6714276934746423 386
0.595918656162612 387
0.5647668263665802 388
0.3821015459895315 389
0.7343527751201422 390
0.5622333613457794 391
0.8082404648118581 392
0.37853891590074384 393
0.6367578296992688 394
0.7212279915739133 395
0.5506462279752931 396
0.5941425740992403 397
0.7003252073356274 398
0.6797276846062608 399
0.6250542480057719 400
0.5880543928376127 401
0.5587569845700647 402
0.4976668915045048 403
0.5773126004325664 404
0.5777593126832679 405
0.5745632713543427 406
0.6632711258910838 407
0.6978755585201812 408
0.6685697617349573 409
0.68618096201264 410
0.655166124985884 411
0.6455549427175475 412
0.5172657296708321 413
0.5839984345526568 414
0.5481626064687459 415
0.4703035848055527 416
0.6928196992485026 417
0.6768313475660506 418
0.6702196417006472 419
0.7209754014752077 420
0.6669741239185746 421
0.6886532039292119 422
0.6500774611052087 423
0.6677050524403112 424
0.5793719335021181 425
0.43450254870803395 426
0.7493133305815713 427
0.5300806359217145 428
0.6585970327987463 429
0.6816267946215393 430
0.7745713540186676 431
0.6467243050728855 432
0.8457046438151008 433
0.6032146457307364 434
0.7763205305184978 435
0.5834710226071149 436
0.706085818743249 437
0.6449015021314687 438
0.7374365299808922 439
0.641245585235259 440
0.6707425709853778 441
0.5887732345894923 442
0.8022341660925281 443
0.7720428547438499 444
0.7426080959449061 445
0.7215746733380235 446
0.6241237511377661 447
0.5661275620476713 448
0.7531294045378281 449
0.7764807545647694 450
0.5497433658398485 451
0.5575654717242784 452
0.6333160740880676 453
0.6490728007093438 454
0.6403726420278163 455
0.49501897050782995 456
0.5133051559677573 457
0.7295762500562368 458
0.6464514499390315 459
0.7460921684584836 460
0.5490052438942639 461
0.5891723364725058 462
0.7733187852021587 463
0.5164484719684508 464
0.6222398692385884 465
0.6794850763459197 466
0.5989512279894839 467
0.6873376373009267 468
0.6499686907052453 469
0.49057360230587765 470
0.5428090323022552 471
0.3508164658868551 472
0.7080528447974518 473
0.7031271246700299 474
0.7665907060310798 475
0.6048412742722522 476
0.6266876706918407 477
0.7329134122932466 478
0.5341640213660812 479
0.5744327663332081 480
0.6002539502420562 481
0.6092629569208162 482
0.5348480550416808 483
0.6142728524083545 484
0.5177834109990749 485
0.6340202799349663 486
0.580616833817162 487
0.7403552895356599 488
0.6327803630134426 489
0.49705952286610566 490
0.7762516855832398 491
0.6032907472468858 492
0.6230778750497636 493
0.6711149326091157 494
0.5490955063885351 495
0.7010983382971443 496
0.6497266995832723 497
0.662544683366166 498
0.7795323473423237 499
0.6826999523531985 500
0.6027389803791059 501
0.5690405646386063 502
0.6312601253402044 503
0.5016925694576614 504
0.6522935144114059 505
0.6670800782514485 506
0.7637638592605606 507
0.6872005248686308 508
0.653506208411383 509
0.63438666819382 510
0.6209850657939675 511
0.637674530006848 512
0.7256045549984693 513
0.6603049367951677 514
0.7836336946930531 515
0.7193365200640333 516
0.7590778743159692 517
0.594545958032956 518
0.6750761117191033 519
0.6941273670972347 520
0.6619266759418373 521
0.4978821678398385 522
0.569751856912904 523
0.5324638912250002 524
0.48393032810095626 525
0.6351341519991034 526
0.6889795484362755 527
0.788110545738469 528
0.6536103013720331 529
0.6277305856975817 530
0.5634309021211761 531
0.6366455039292884 532
0.7375393810172737 533
0.5087819208686399 534
0.5793758408851262 535
0.6378453193887574 536
0.5299018648032976 537
0.6776950709298335 538
0.57583553761528 539
0.6923028811531111 540
0.6551564023968293 541
0.6790216864027617 542
0.5829890733607237 543
0.7297488830297452 544
0.4633343444596709 545
0.7138474909912589 546
0.3236746201330315 547
0.7312968618456605 548
0.5021010708194802 549
0.6214109790949175 550
0.6739542317649387 551
0.5929292328647564 552
0.7245080630978784 553
0.6241874759424406 554
0.7147280252372686 555
0.5554055959871904 556
0.5143996908993878 557
0.6955323091651009 558
0.7086465948671332 559
0.6141859630599776 560
0.4935634211922366 561
0.7054139815324014 562
0.5894119757996744 563
0.6583865451126286 564
0.6745328774272308 565
0.8056110716855966 566
0.660168754771259 567
0.7076335276140324 568
0.6540808487617522 569
0.6403359508959029 570
0.6471116036020039 571
0.6850195048832569 572
0.624404320265255 573
0.5746221014405681 574
0.6908206739054338 575
0.6784453683966711 576
0.7610538612828168 577
0.6666301618567659 578
0.6317936894364945 579
0.593348327398521 580
0.6461129223754165 581
0.49720633314994456 582
0.6153327529073316 583
0.5219281584244497 584
0.5789408190042764 585
0.6937938063311775 586
0.6261978618607282 587
0.7001460001703348 588
0.6931595526188677 589
0.5895221336798071 590
0.6973342239240363 591
0.7181817497416922 592
0.7177869579117071 593
0.6050803189453224 594
0.38745650602372916 595
0.5581152967016262 596
0.5620157772426413 597
0.5642712989330513 598
0.5258320104542691 599
0.5140570075768967 600
0.5705769264832609 601
0.7111524130449016 602
0.5858088286416365 603
0.5747150814869991 604
0.7394849583764886 605
0.4860229942453037 606
0.6078031786212126 607
0.683095528859843 608
0.6440413976251727 609
0.47376119335487754 610
0.5892544661013335 611
0.61852782091698 612
0.6028283255559854 613
0.6678912866839212 614
0.5918332278758884 615
0.37129371198923333 616
0.5820934689213697 617
0.6802472820328236 618
0.6068354532984561 619
0.5097366136740408 620
0.7211793950662957 621
0.6029651349269856 622
0.5126903741881339 623
0.7505496544162558 624
0.5958211331801343 625
0.693666392612403 626
0.513029176347533 627
0.6716331197406875 628
0.644414234103071 629
0.5864349006207039 630
0.7093200462230523 631
0.7051955841776358 632
0.643287488987436 633
0.5160436431904742 634
0.5842606255503107 635
0.6789637886473447 636
0.6658581432037816 637
0.7586452161575572 638
0.5432321278872814 639
0.5651150278126675 640
0.6711239254818326 641
0.6828303159575017 642
0.6024772251939865 643
0.5159956236938126 644
0.6955557582166756 645
0.5973828530791114 646
0.4451914982617279 647
0.6039961164996772 648
0.6484691529124612 649
0.6752864923463341 650
0.6152413085402 651
0.7503736812354729 652
0.7693049243088173 653
0.6502214147834349 654
0.6499166373471279 655
0.5853845537975679 656
0.46074232531090775 657
0.6752893069831232 658
0.6564612639755687 659
0.725572994545657 660
0.7687202588296986 661
0.5483032096205573 662
0.5151820482796892 663
0.4798164754566363 664
0.6786794733296417 665
0.6144566814741835 666
0.6989412353906306 667
0.7160710030587714 668
0.737153396958796 669
0.7504080455352193 670
0.5216293416118821 671
0.6650567426801142 672
0.7328397874737423 673
0.6646334453717525 674
0.6286912587726341 675
0.6620493423331657 676
0.5819321144913536 677
0.717755637262929 678
0.6633774647766782 679
0.6212011499095711 680
0.5238893098159141 681
0.7208128497583788 682
0.6986235390119429 683
0.5896420635430756 684
0.6219774744713524 685
0.8314035486725534 686
0.6330517529327403 687
0.5681586492140231 688
0.793194893542522 689
0.5890971151820641 690
0.6814867258740506 691
0.6489522093517218 692
0.6541374910813782 693
0.6938693661889209 694
0.7115381292275493 695
0.6608423009125732 696
0.5533655302812126 697
0.7515853834999975 698
0.6663150731251876 699
0.47694487533230434 700
0.7039520744463661 701
0.6011927294814357 702
0.7293925877909873 703
0.5353884884379168 704
0.6439475684211502 705
0.7267569545100503 706
0.660442785352964 707
0.6549454178161755 708
0.5332407643363088 709
0.6448966026345786 710
0.678448996989173 711
0.8112925645871688 712
0.80103894161041 713
0.6568240430725163 714
0.677862391268359 715
0.7207746610708963 716
0.7319755612077556 717
0.3421600639183012 718
0.6459333992190612 719
0.5521193513019789 720
0.5873472429006286 721
0.6768796368301333 722
0.6734832659259693 723
0.6449835464037634 724
0.6219729363355897 725

0.6519900191756327 726
0.6891881310575161 727
0.5977228448515273 728
0.5800396975191343 729
0.740295472826717 730
0.5285981186089523 731
0.7939752841466234 732
0.6719937872754016 733
0.5889158679040558 734
0.544391401541061 735
0.6117864672176958 736
0.5038430593187364 737
0.7121580634777918 738
0.5987506143284823 739
0.6287819738260423 740
0.5937085175836527 741
0.7512010453847741 742
0.7376199670273209 743
0.5493130081672706 744
0.6130905130956398 745
0.6541684590382839 746
0.553020750171736 747
0.5927191442322008 748
0.5104260352538985 749
0.5510485202577099 750
0.705901245153438 751
0.7641635569706875 752
0.7269724155371375 753
0.7142766645687885 754
0.6192980350051087 755
0.6072752757422109 756
0.7491026692415355 757
0.61117179425284 758
0.6332233148671855 759
0.6523251794943961 760
0.6657607521476905 761
0.7119934400921496 762
0.6428490843289215 763
0.6178813599331638 764
0.6603847365777733 765
0.6258692863623625 766
0.6269423256636766 767
0.5344138070744149 768
0.7578414546913523 769
0.6293856649990772 770
0.6976424434781576 771
0.6907281284849137 772
0.6080628793909253 773
0.5576933991713684 774
0.5851308105245022 775
0.553690650090521 776
0.3628674193470447 777
0.7045214118264764 778
0.6731685992212864 779
0.6546645105348425 780
0.8251494226592042 781
0.7073935351384749 782
0.7833874419966821 783
0.641012754439459 784
0.6341838665461661 785
0.6375304071096658 786
0.6497317981848898 787
0.7001402190395098 788
0.43049626265604823 789
0.7190170683800845 790
0.7028343920692907 791
0.7349615682737807 792
0.7383174287180321 793
0.657821308239688 794
0.5603500015333613 795
0.7151022464118788 796
0.6066234131167011 797
0.6343501019504197 798
0.7499225836270309 799
0.6404889093846782 800
0.5073483806883843 801
0.6130117660944525 802
0.6533081847372489 803
0.536942561262814 804
0.5976534016698927 805
0.6454850825576003 806
0.7460076382812872 807
0.3888227559388878 808
0.5655208686121189 809
0.5549735774957862 810
0.6485745559361265 811
0.6714457598927528 812
0.525850219038957 813
0.7881347100870552 814
0.6277784734090079 815
0.5990351787298008 816
0.6931303446719198 817
0.6568998617986865 818
0.6534881961127502 819
0.5586349285463306 820
0.7774076727230057 821
0.6599094948887139 822
0.5951115923751658 823
0.44789709430568736 824
0.7314008230911404 825
0.664315796961207 826
0.7854181376104485 827
0.6538662004063587 828
0.6379995401462113 829
0.4770112089316083 830
0.708898557431352 831
0.7752647765830002 832
0.5806164186441691 833
0.7484601428848563 834
0.6403099113016302 835
0.5741456062759853 836
0.6388393186599428 837
0.6208487174513677 838
0.59466805105165 839
0.7293165186904773 840
0.7584262712922198 841
0.7251977914245142 842
0.7080938425001275 843
0.6551090339280732 844
0.4946983031139339 845
0.6089889766620294 846
0.6132540525497128 847
0.5751253750348058 848
0.6888899147664374 849
0.7279070100641443 850
0.6005509572197728 851
0.6351515722924191 852
0.6227497910204782 853
0.5506774958534679 854
0.6332370527304649 855
0.5421039790654507 856
0.5023521327212066 857
0.7453799395821925 858
0.5257356515490074 859
0.7757751274967454 860
0.5694155458660123 861
0.6647823327450764 862
0.5779347752499404 863
0.6698536108976036 864
0.5567283925388855 865
0.6244800426500927 866
0.5831992169586616 867
0.5598564819714074 868
0.633235570662193 869
0.5749845147467302 870
0.466761880139548 871
0.6640036605693609 872
0.6209493880328099 873
0.6864673222401542 874
0.6563655478053001 875
0.644616238340948 876
0.5437479291153295 877
0.6364430627754852 878
0.6404153370100629 879
0.7023595409943213 880
0.6992355328565534 881
0.6545023660637261 882
0.729754175658461 883
0.7363038789782106 884
0.6279870392807643 885
0.539330916518456 886
0.7145687629541919 887
0.5719635838991695 888
0.5825778572979529 889
0.6714898946392907 890
0.5280749239827831 891
0.6843144613901346 892
0.6379574830086878 893
0.5129382107423714 894
0.4810999641611934 895
0.6025197289738959 896
0.6927463849747462 897
0.7568832086185829 898
0.6214034350527158 899
0.6837548304428556 900
0.6283047713232803 901
0.5600476269360524 902
0.7556606173927638 903
0.7050249623907888 904
0.5950490014176186 905
0.7854552766801078 906
0.6507825073868445 907
0.6795973171733433 908
0.6772667459818482 909
0.7173657365976773 910
0.696205795676679 911
0.5239833162652263 912
0.5723589218121349 913
0.6665380346280771 914
0.6652108779699525 915
0.4977700184943331 916
0.5032791655351739 917
0.7261703722290581 918
0.46683353166177877 919
0.49937960677272064 920
0.6598300440365397 921
0.7814442907843024 922
0.6534043760141099 923
0.5812678917197075 924
0.5697187215701145 925
0.7876427384825428 926
0.6176168759145253 927
0.6737525019608801 928
0.7424364256370986 929
0.5259681062607355 930
0.7153295884238944 931
0.49568025850565844 932
0.7141083888641864 933
0.6326736408044091 934
0.5527190007037144 935
0.6317296385417498 936
0.5531149922184991 937
0.7529647411565782 938
0.5118550756485645 939
0.5211479308569642 940
0.5606808162304118 941
0.6917554555016904 942
0.6340946515614103 943
0.670316722414181 944
0.7404621288446711 945
0.5021583614645566 946
0.5742091166402561 947
0.6728772750847409 948
0.737452129815646 949
0.4986915602425961 950
0.6104013500070483 951
0.7186873659246986 952
0.6509363987290078 953
0.6502758461178235 954
0.6382730771720522 955
0.5748809766148599 956
0.6788325374189301 957
0.7221446075818998 958
0.6466685957578762 959
0.4483840562764042 960
0.6300457737142892 961
0.6460727616323912 962
0.5201699395723038 963
0.5641765321752665 964
0.5897583924730787 965
0.7199655201788842 966
0.7809774323763801 967
0.667152209122186 968
0.7286957385374302 969
0.4828449699874324 970
0.5644004547104724 971
0.6908817840448958 972
0.5349890371136303 973
0.7344285551135062 974
0.5858904814953411 975
0.6210685918673238 976
0.7392436784687813 977
0.5711209879235264 978
0.4662804871952889 979
0.5742725187726122 980
0.7648798132065588 981
0.6532721559164574 982
0.6934803693923199 983
0.5359258305546164 984
0.5821002749099562 985
0.7718151986924648 986
0.5998498096298388 987
0.641930453059536 988
0.7792984408127136 989
0.5780910583452539 990
0.5178399929881359 991
0.6969796542569674 992
0.6501633021082326 993
0.6533768014725854 994
0.6284767202386419 995
0.7158424528766222 996
0.7113402620710477 997
0.6034245114775413 998
0.5926684087890187 999

In [48]:
np.argmax(scores)

433

In [50]:
scores[np.argmax(scores)]

0.8457046438151008

In [51]:
#train model for best randome split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state =np.argmax(scores) )
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
r2_score(y_test,y_pred)

0.8457046438151008

In [52]:
import pickle

In [55]:
pickle.dump(pipe, open("LinearRegressionModel.pkl", "wb"))

In [58]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns= ['name','company','year','kms_driven','fuel_type'])) #example query

array([458899.18891749])